### PR TITLE
Add clang linter

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description
- Add clang linter
- Add dependabot (github action dependencies only)

## Type of Change
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the documentation blocks for new or existing components

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
The modified c++ files are the results of the linter. The action uploads them as an artifact.

**Comment by TheElixZammuto** [comment]
What happens if the linter finds errors in the code style? Does it fail the pipeline or it just provides the changed files?

**Comment by ReenigneArcher** [comment]
> What happens if the linter finds errors in the code style? Does it fail the pipeline or it just provides the changed files?

It's a matrix strategy. So when "inplace" is true the workflow succeeds and the artifacts are uploaded. Then it runs with "inplace" as false and will fail the workflow if there are errors.

The latest failure should show that as an example.

**Comment by TheElixZammuto** [comment]
> > What happens if the linter finds errors in the code style? Does it fail the pipeline or it just provides the changed files?
> 
> It's a matrix strategy. So when "inplace" is true the workflow succeeds and the artifacts are uploaded. Then it runs with "inplace" as false and will fail the workflow if there are errors.
> 
> The latest failure should show that as an example.
Gotcha, so it's the best of both worlds! ^_^

**Review by TheElixZammuto — APPROVED** [review]

**Pull request merged**
