### PR TITLE
Fix references to loki repo in README.md

### PR DESCRIPTION
**Pull request by KuleRucket**
Fix references to loki repo

## Description

Just changes the git location

### Screenshot

Include screenshots if the changes are UI-related.

### Issues Fixed or Closed

- Fixes #(issue)

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the documentation blocks for new or existing components

### CODE REVIEW

**Comment by Azmiko46** [comment]
@ReenigneArcher please check it, it's neccessary for avoid new people clone the old repository instead the new.

**Comment by ReenigneArcher** [comment]
@Azmiko46 I know about every single issue and PR here, you don't need to tag me.

Most likely this won't be merged as the documentation is going to be completely overhauled soon.

**Comment by Azmiko46** [comment]
Hi, thanks very much for answer me!
Sorry for the ping than I made :(

**Comment by ReenigneArcher** [comment]
Superseded by #134

**Pull request closed without merging**
