### PR TITLE
Publish to Winget workflow

### PR DESCRIPTION
**Pull request by sitiom**
## Description

This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:

1. Add a PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN` (or rename the secret name in the workflow).
2. Fork https://github.com/microsoft/winget-pkgs under @SunshineStream

### Issues Fixed or Closed

- Resolves https://github.com/SunshineStream/Sunshine/discussions/201

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
You should discuss this stuff with us on discord before wasting your time. I'm not planning on supporting a ton of third party packaging systems.

**Comment by ReenigneArcher** [comment]
> I see. You could have left your comment on https://github.com/SunshineStream/Sunshine/discussions/201 so I would know. I also assumed you were willing to support it, seeing that you were planning to use aurpublish before in #39.

I didn't have time before you made this PR. You've been kind of spamming this repo since the last release. Where were you when I was asking for testers on both discords for the last 4 months?

Initially when I started maintaining this I was planning to use aurpublish but have since had a change of direction after discussing with more seasoned developers, if you noticed that issue is closed and we're not publishing to the aur. It's maintained by a third party. Also Linux is a different world than Windows as every distro has different run time requirements. For Windows, a single build of sunshine basically works on any build of windows, so not much benefit to distributing the same thing in a bunch of places.

**Comment by sitiom** [comment]
> You've been kind of spamming this repo since the last release.

Sorry, you were locking the discussions every time, so I couldn't ask what the best way to open them was. I was also trying to keep them separate as they are technically two different things.

> Where were you when I was asking for testers on both discords for the last 4 months?

I don't check Discord that much, and upon checking the announcement, there was no ping, so that didn't help either into getting notified about it.

> Initially when I started maintaining this I was planning to use aurpublish but have since had a change of direction after discussing with more seasoned developers, if you noticed that issue is closed and we're not publishing to the aur. It's maintained by a third party. Also Linux is a different world than Windows as every distro has different run time requirements. For Windows, a single build of sunshine basically works on any build of windows, so not much benefit to distributing the same thing in a bunch of places.

But understood, I'll just respect your decision of not supporting third-party packaging systems.

**Comment by ReenigneArcher** [comment]
> I don't check Discord that much, and upon checking the announcement, there was no ping, so that didn't help either into getting notified about it.

No problem. In the future please discuss with us on Discord before opening an issue. Sorry, I probably overreacted about all the discussions being opened. I'm trying to keep this project/repo from getting too overwhelming like the original... probably the reason it's no longer maintained. Everything you opened could easily be created as a single issue such as `v0.14.0 windows package issues` or something similar.

> But understood, I'll just respect your decision of not supporting third-party packaging systems.

It doesn't mean we won't in the future, but for now I'm going to pass on officially supporting any Windows packaging systems... I just don't have the bandwidth to test everything by myself and it's very difficult to get anyone to help test.

Initial third party repos to support are going to these:

- macports (this is waiting on https://github.com/macports/macports-ports/pull/15143)
- flatpak hub (this is waiting on #195 )
- appimage hub (this is waiting on resolution of #151 )
- docker hub (this is waiting on #145 )

Following resolution on each of these, there are a lot of things to fix up in the CI before automating any of this.

**Comment by sitiom** [comment]
Btw, this PR is just six lines long (excluding whitespace). Surely this isn't hard to test out? Winget just calls the installer, so the experience should be the same as if you used the installer by itself.

**Comment by ReenigneArcher** [comment]
It's difficult to test considering it only should run on a push event into "master" ... Which here is how a release is made.

Also I would need to review their action, but I highly doubt it will work as you expect.

**Comment by sitiom** [comment]
> It's difficult to test considering it only should run on a push event into "master" ... Which here is how a release is made.
> 
> Also I would need to review their action, but I highly doubt it will work as you expect.
> 
> There are also very few workflows I trust to have access to a PAT.

You can check the [docs](https://bittu.eu.org/docs/wr-intro/) for that. You can also look at the other repos [using the action](https://github.com/vedantmgoyal2009/vedantmgoyal2009/network/dependents). In general, the workflow would be:
1. A release is made
2. The action searches for the new artifacts in the release
3. The manifest is updated, and a PR is made with your PAT. Example: https://github.com/microsoft/winget-pkgs/pull/63449

**Comment by ReenigneArcher** [comment]
This is a bit unusual. All projects in one repo... https://github.com/vedantmgoyal2009/vedantmgoyal2009

Documentation on the release action is minimal. https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation/releaser-action

Please share the documentation for manually creating a new release on winget. I already have an idea for how to create a PR, which is the same way all of the above will be done, except docker.

**Comment by sitiom** [comment]
> This is a bit unusual. All projects in one repo... [vedantmgoyal2009/vedantmgoyal2009](https://github.com/vedantmgoyal2009/vedantmgoyal2009)

I read somewhere (forgot where it is) that it would be hard to maintain them separately, according to the maintainer. Once the WinGet Automation Bot has been officially merged to winget-pkgs, the action would be separated and all actions would be updated to point to the new location.

> Documentation on the release action is minimal. [vedantmgoyal2009/vedantmgoyal2009@`main`/winget-pkgs-automation/releaser-action](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation/releaser-action)

These are the [docs](https://bittu.eu.org/docs/wr-intro) for the releaser action.

> Please share the documentation for manually creating a new release on winget. I already have an idea for how to create a PR, which is the same way all of the above will be done, except docker.

[Here](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example). There are two tools to do it: [`wingetcreate`](https://github.com/microsoft/winget-create) and [`YamlCreate.ps1`](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1). In my experience, `YamlCreate.ps1` is better (which is what the action also uses behind the scenes).

**Comment by sitiom** [comment]
It seems like the action is being separated now: https://github.com/vedantmgoyal2009/winget-releaser

**Comment by ReenigneArcher** [comment]
I can't re-open as the branch was deleted... but I will re-consider this. Please be patient though.

**Comment by sitiom** [comment]
New PR as draft? #215

**Comment by vedantmgoyal2009** [comment]
@ReenigneArcher any updates?

**Comment by ReenigneArcher** [comment]
@vedantmgoyal2009 no

**Pull request closed without merging**
