### PR TITLE
Automated PR tests and releases

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

- Added CHANGELOG.md
- Add build checks
- Add automated release
  - CHANGELOG.md version must not match latest released tag_name
  - CHANGELOG version is compared to latest released version on Pull Request into master
- Added Fedora build Dockerfiles (no packaging yet)
- Improved readability of Dockerfiles
- Use `update-alternatives` instead of `cp` for older Ubuntu distros
- Added AppImage

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the documentation blocks for new or existing components

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
I apologize for all the commits. Workflows are not the easiest thing to test.

Here is a workflow run for creating a new release (when the release version was updated): https://github.com/ReenigneArcher/Sunshine/actions/runs/1683355353

And here is a workflow run when the release version was not updated in the CHANGELOG.md (this should also be caught when the PR is created against the `master` branch): https://github.com/ReenigneArcher/Sunshine/actions/runs/1683445817

**Comment by ReenigneArcher** [comment]
This needs a little tweaking on the create release action due to the multiple steps, it fails on all except the first build. I have an idea to fix it though.

**Comment by ReenigneArcher** [comment]
Updated Examples:

**PR into nightly branch**
https://github.com/ReenigneArcher/Sunshine/actions/runs/1685200094
-No check on CHANGELOG.md
-Build each version
-Package everything except Fedora
-Upload artifacts

**PR into master branch**
When the release version from the changelog matches the latest released version: https://github.com/ReenigneArcher/Sunshine/actions/runs/1685245727/attempts/1
-Intentionally fail the workflow (gives an opportunity to fix the CHANGELOG.md before accepting the PR)
-Build each version
-Package everything except Fedora
-Upload artifacts

Release version in changelog was updated and does not match latest released version: https://github.com/ReenigneArcher/Sunshine/actions/runs/1685245727/attempts/2
-Same as attempt 1 except workflow passes beyond changelog check

**push into master branch**
https://github.com/ReenigneArcher/Sunshine/actions/runs/1685294883
- Harder to fix anything at this point so:
  - The check on changelog is done earlier when the PR is made into master

**Example of Created Release**
https://github.com/ReenigneArcher/Sunshine/releases/tag/0.0.0

**Comment by TheElixZammuto** [comment]
Not an expert on the GitHub actions side, so all I can say is LGTM for the workflow side of things

**Review by TheElixZammuto — APPROVED** [review]

**Pull request merged**
